version: "3"
services:
    app:
        image: imdb-mongo:5.6
        build: .
        depends_on:
            - db_host
        ports:
          - 5001:5001
        networks:
         app_net:
            ipv4_address: 172.24.2.1
    db_host:
        image: mongo:latest
        ports:
          - 27018:27017
        networks:
         app_net:
            ipv4_address: 172.24.2.2

networks:
 app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/16"
